### PR TITLE
[gmp-droid] Convert color format according to encoder capabilities. JB#55092

### PR DESCRIPTION
**Pull request by d-grigorev**

### CODE REVIEW

**Comment by d-grigorev** [comment]
This uses `droid_media_codec_get_supported_color_formats()` introduced in https://github.com/sailfishos/droidmedia/pull/83.

**Review by adenexter — APPROVED** [review]

**Comment by d-grigorev** [comment]
Changes since previous version:
* Select the top-most supported frame format in the list
* Avoid compile warning by casting android's format variable type to int

**Review by adenexter — APPROVED** [review]

**Comment by mlehtima** [comment]
I think we need to change the droidmedia API a little because the current way doesn't take into account the same metadata (for example hardware vs software codecs) as the other calls and uses a different way to find matching codec and therefore could find a different codec with different supported color formats. Change for the API and some other fixes in https://github.com/sailfishos/droidmedia/pull/87

**Comment by d-grigorev** [comment]
Changed according to https://github.com/sailfishos/droidmedia/pull/87.

**Review by okodron — APPROVED** [review]

**Pull request merged**
